# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish-nuget
on:
  release:
    types: [published]

  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get all history to allow automatic versioning using MinVer

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --no-restore --verbosity normal

      - name: Publish NuGet package
        run: |
          foreach ($file in Get-ChildItem -Recurse -Path . -Filter *.nupkg) {
            dotnet nuget push $file --api-key "${{ secrets.NUGET_PAT }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: lassevk/LVK.TopoSort